export const canadianProvinces = [
    { label: "Alberta", value: "AB" },
    { label: "British Columbia", value: "BC" },
    { label: "Manitoba", value: "MB" },
    { label: "New Brunswick", value: "NB" },
    { label: "Newfoundland and Labrador", value: "NL" },
    { label: "Northwest Territories", value: "NT" },
    { label: "Nova Scotia", value: "NS" },
    { label: "Nunavut", value: "NU" },
    { label: "Ontario", value: "ON" },
    { label: "Prince Edward Island", value: "PE" },
    { label: "Quebec", value: "QC" },
    { label: "Saskatchewan", value: "SK" },
    { label: "Yukon", value: "YT" },
];

export const americanStates = [
    { code: "AL", label: "Alabama" },
    { code: "AK", label: "Alaska" },
    { code: "AZ", label: "Arizona" },
    { code: "AR", label: "Arkansas" },
    { code: "CA", label: "California" },
    { code: "CO", label: "Colorado" },
    { code: "CT", label: "Connecticut" },
    { code: "DE", label: "Delaware" },
    { code: "FL", label: "Florida" },
    { code: "GA", label: "Georgia" },
    { code: "HI", label: "Hawaii" },
    { code: "ID", label: "Idaho" },
    { code: "IL", label: "Illinois" },
    { code: "IN", label: "Indiana" },
    { code: "IA", label: "Iowa" },
    { code: "KS", label: "Kansas" },
    { code: "KY", label: "Kentucky" },
    { code: "LA", label: "Louisiana" },
    { code: "ME", label: "Maine" },
    { code: "MD", label: "Maryland" },
    { code: "MA", label: "Massachusetts" },
    { code: "MI", label: "Michigan" },
    { code: "MN", label: "Minnesota" },
    { code: "MS", label: "Mississippi" },
    { code: "MO", label: "Missouri" },
    { code: "MT", label: "Montana" },
    { code: "NE", label: "Nebraska" },
    { code: "NV", label: "Nevada" },
    { code: "NH", label: "New Hampshire" },
    { code: "NJ", label: "New Jersey" },
    { code: "NM", label: "New Mexico" },
    { code: "NY", label: "New York" },
    { code: "NC", label: "North Carolina" },
    { code: "ND", label: "North Dakota" },
    { code: "OH", label: "Ohio" },
    { code: "OK", label: "Oklahoma" },
    { code: "OR", label: "Oregon" },
    { code: "PA", label: "Pennsylvania" },
    { code: "RI", label: "Rhode Island" },
    { code: "SC", label: "South Carolina" },
    { code: "SD", label: "South Dakota" },
    { code: "TN", label: "Tennessee" },
    { code: "TX", label: "Texas" },
    { code: "UT", label: "Utah" },
    { code: "VT", label: "Vermont" },
    { code: "VA", label: "Virginia" },
    { code: "WA", label: "Washington" },
    { code: "WV", label: "West Virginia" },
    { code: "WI", label: "Wisconsin" },
    { code: "WY", label: "Wyoming" },
];

export const canadaDict = {
    ab: "AB",
    alberta: "AB",
    bc: "BC",
    "british columbia": "BC",
    manitoba: "MB",
    mb: "MB",
    nb: "NB",
    "new brunswick": "NB",
    "newfoundland and labrador": "NL",
    nl: "NL",
    "northwest territories": "NT",
    "nova scotia": "NS",
    ns: "NS",
    nt: "NT",
    nu: "NU",
    nunavut: "NU",
    on: "ON",
    ontario: "ON",
    pe: "PE",
    "prince edward island": "PE",
    qc: "QC",
    quebec: "QC",
    saskatchewan: "SK",
    sk: "SK",
    yt: "YT",
    yukon: "YT",
};

export const usaDict = {
    ak: "AK",
    al: "AL",
    alabama: "AL",
    alaska: "AK",
    ar: "AR",
    arizona: "AZ",
    arkansas: "AR",
    az: "AZ",
    ca: "CA",
    california: "CA",
    co: "CO",
    colorado: "CO",
    connecticut: "CT",
    ct: "CT",
    de: "DE",
    delaware: "DE",
    fl: "FL",
    florida: "FL",
    ga: "GA",
    georgia: "GA",
    hawaii: "HI",
    hi: "HI",
    ia: "IA",
    id: "ID",
    idaho: "ID",
    il: "IL",
    illinois: "IL",
    in: "IN",
    indiana: "IN",
    iowa: "IA",
    kansas: "KS",
    kentucky: "KY",
    ks: "KS",
    ky: "KY",
    la: "LA",
    louisiana: "LA",
    ma: "MA",
    maine: "ME",
    maryland: "MD",
    massachusetts: "MA",
    md: "MD",
    me: "ME",
    mi: "MI",
    michigan: "MI",
    minnesota: "MN",
    mississippi: "MS",
    missouri: "MO",
    mn: "MN",
    mo: "MO",
    montana: "MT",
    ms: "MS",
    mt: "MT",
    nc: "NC",
    nd: "ND",
    ne: "NE",
    nebraska: "NE",
    nevada: "NV",
    "new hampshire": "NH",
    "new jersey": "NJ",
    "new mexico": "NM",
    "new york": "NY",
    nh: "NH",
    nj: "NJ",
    nm: "NM",
    "north carolina": "NC",
    "north dakota": "ND",
    nv: "NV",
    ny: "NY",
    oh: "OH",
    ohio: "OH",
    ok: "OK",
    oklahoma: "OK",
    or: "OR",
    oregon: "OR",
    pa: "PA",
    pennsylvania: "PA",
    "rhode island": "RI",
    ri: "RI",
    sc: "SC",
    sd: "SD",
    "south carolina": "SC",
    "south dakota": "SD",
    tennessee: "TN",
    texas: "TX",
    tn: "TN",
    tx: "TX",
    ut: "UT",
    utah: "UT",
    va: "VA",
    vermont: "VT",
    virginia: "VA",
    vt: "VT",
    wa: "WA",
    washington: "WA",
    "west virginia": "WV",
    wi: "WI",
    wisconsin: "WI",
    wv: "WV",
    wy: "WY",
    wyoming: "WY",
};
